name: 'Terraform'
on: [push]
   
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
     AWS_SECRET_KEY_ID: ${{ secrets.AWS_SECRET_KEY }}
     AWS_REGION: 'ap-south-1'
      
    steps:
     - name: Checkout
       uses: actions/checkout@v2
       
     - name: Setup Terraform
       uses: hashicorp/setup-terraform@v1
       
     - name: Terraform Init
       id: init
       run: terraform init
       
     - name: Terraform Plan
       id: plan
       run: terraform plan
       
       
